[Xorg_glproto]
git-tree-sha1 = "ded08aec3019c136d5651212890625ae2cf1e02e"

    [[Xorg_glproto.download]]
    sha256 = "c427bdad36419389c4791a2d1a94f28e0e8c836b6c5b2163faf34245b466cce1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_glproto_jll.jl/releases/download/Xorg_glproto-v1.4.17+2/Xorg_glproto.v1.4.17.any.tar.gz"
