[Xorg_glproto]
git-tree-sha1 = "61e190bb00a8c3d7a8115c1c856ebe1995a82017"

    [[Xorg_glproto.download]]
    sha256 = "2aa56e3f91cd7e494a92f4c8e7931edfbd2e4277961297eede6e6333e1f643a5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_glproto_jll.jl/releases/download/Xorg_glproto-v1.4.17+1/Xorg_glproto.v1.4.17.any.tar.gz"
